---
abstract: 'is given() too much typing for you?'
author:
  - 'Ben Hengst <ben.hengst@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Given-Hash
requires:
  Exporter: 0
  List::MoreUtils: 0.33
  Test::More: 0.98
  perl: 5.014
version: 0.007
